version: '3.8'

services:
  web:
    build: ./service
    #command: python manage.py run -h 0.0.0.0
    #volumes:
    #  - ./service/web/:/usr/src/app/
    ports:
      - "5000:5000"
    env_file:
      - service/.env

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web