version: '3.8'

services:
  web:
    build: ./web
    #volumes:
    #  - ./service/web/:/usr/src/app/
    ports:
      - "5000:5000"
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web